$base = "C:\Users\Pc\Desktop\laravel skills from every thing claude code\research\workspaces\cost-resource-optimization"
$date = "2026-06-03"

function Write-TreeFile {
    param($Path, $Trees, $Title, $Domain, $Subdomain)
    
    $lines = @()
    $lines += "# Metadata"
    $lines += ""
    $lines += "**Domain:** $Domain"
    $lines += "**Subdomain:** $Subdomain"
    $lines += "**Knowledge Unit:** $Title"
    $lines += "**Generated:** $date"
    $lines += ""
    $lines += "---"
    $lines += ""
    $lines += "# Decision Inventory"
    $lines += ""
    $i = 1
    foreach ($t in $Trees) {
        $lines += "$i. $($t.name)"
        $i++
    }
    $lines += ""
    $lines += "---"
    $lines += ""
    $lines += "# Architecture-Level Decision Trees"
    $lines += ""
    
    foreach ($t in $Trees) {
        $lines += "---"
        $lines += ""
        $lines += "## Decision Name: $($t.name)"
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Decision Context"
        $lines += ""
        $lines += $t.context
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Decision Criteria"
        $lines += ""
        $lines += $t.criteria
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Decision Tree"
        $lines += ""
        $lines += $t.tree
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Rationale"
        $lines += ""
        $lines += $t.rationale
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Recommended Default"
        $lines += ""
        $lines += "**Default:** $($t.default)"
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Risks Of Wrong Choice"
        $lines += ""
        $lines += $t.risk
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Related Rules"
        $lines += ""
        $lines += "Rule: Follow standardized $Title practices"
        $lines += ""
        $lines += "---"
        $lines += ""
        $lines += "## Related Skills"
        $lines += ""
        $lines += "Analyze and Optimize $Title"
        $lines += ""
        $lines += "---"
        $lines += ""
    }
    
    $content = $lines -join "`n"
    Set-Content -Path $Path -Value $content -Encoding UTF8
}

# Collect KUs to process
$kus = Get-ChildItem -Path $base -Directory | Where-Object { $_.Name -match '^\d{2}-' } | ForEach-Object {
    $sub = $_.FullName
    Get-ChildItem -Path $sub -Directory | ForEach-Object {
        $std = Join-Path $_.FullName "04-standardized-knowledge.md"
        $dt = Join-Path $_.FullName "07-decision-trees.md"
        if ((Test-Path $std) -and -not (Test-Path $dt)) {
            [PSCustomObject]@{
                Subdomain = (Split-Path $sub -Leaf)
                KU = $_.Name
                Path = $_.FullName
            }
        }
    }
}

$total = ($kus | Measure-Object).Count
Write-Host "Processing $total KUs..."
$count = 0

foreach ($ku in $kus) {
    $count++
    Write-Progress -Activity "Generating 07-decision-trees.md" -Status "$($ku.Subdomain)/$($ku.KU)" -PercentComplete (($count/$total)*100)
    
    $stdPath = Join-Path $ku.Path "04-standardized-knowledge.md"
    $rulesPath = Join-Path $ku.Path "05-rules.md"
    $outPath = Join-Path $ku.Path "07-decision-trees.md"
    
    # Get title
    $title = (Get-Content -Path $stdPath -TotalCount 1).Trim('# ')
    if ([string]::IsNullOrWhiteSpace($title)) { $title = $ku.KU -replace '-', ' ' }
    
    # Get rules
    $ruleTexts = @()
    if (Test-Path $rulesPath) {
        $rc = Get-Content -Path $rulesPath
        foreach ($rl in $rc) {
            if ($rl -match '^## (.+)') { $ruleTexts += $matches[1] }
        }
    }
    
    # Build domain/subdomain display names
    $domainDisp = "Cost Resource Optimization"
    $subDisp = $ku.Subdomain
    
    # Generate trees based on KU
    $trees = @()
    
    # Use a switch -Regex approach for flexibility
    switch -Regex ($ku.KU) {
        '^vm-sizing' {
            $trees += @{name="Instance Family Selection"; context="Choose between Graviton (ARM) and x86 instance families for Laravel workloads."; criteria="cost, performance, compatibility"; tree="New deployment or existing migration?`n`nNEW -> Use Graviton (m7g/r7g/c7g) -- 20% cheaper, identical PHP performance`nEXISTING -> Currently on x86?`n  YES -> Has native x86 binary dependencies?`n    YES -> Stay on x86 until dependencies are ported`n    NO -> Migrate to Graviton via staging first`n  NO -> Already optimal`n`nWorkload profile?`nCPU-bound (image processing) -> c7g instances`nMemory-bound (large cache) -> r7g instances`nBalanced (web serving) -> m7g instances`nBurstable (low traffic) -> t4g instances"; rationale="Graviton offers 20% cost reduction with identical PHP execution performance. Choosing the right instance family matches resources to actual workload requirements."; default="Graviton m7g for balanced workloads; c7g for CPU-bound; r7g for memory-bound"; risk="Using t4g for sustained production causes CPU credit exhaustion. Wrong family wastes memory, CPU, or network capacity."}
            $trees += @{name="Instance Size Right-Sizing via Monitoring"; context="Determine optimal instance size based on actual utilization metrics over 2-week period."; criteria="cost, performance"; tree="Current CPU utilization (2-week P95)?`n`n< 20% -> Downsize one tier (xlarge to large)`n20-60% -> Current size appropriate`n> 60% -> Consider upsizing or scaling out`n`nMemory utilization (peak)?`n< 50% -> Reduce instance memory or downsize family`n50-80% -> Appropriate sizing`n> 80% -> Increase memory or scale out`n`nTraffic pattern?`nSteady -> Right-size for average + 20% headroom`nVariable -> Use Auto Scaling, size for baseline only"; rationale="Single-day monitoring misses weekend lows and peak hours. Two-week data reveals true baseline and peak, preventing both over-provisioning and under-provisioning."; default="Start with m7g.large, monitor for 2 weeks, right-size based on P95 utilization"; risk="Sizing for peak without Auto Scaling wastes 40-70% of compute budget on idle capacity."}
            $trees += @{name="Burstable vs Dedicated CPU Decision"; context="Choose between t4g (burstable with CPU credits) and m7g (dedicated CPU) instances."; criteria="cost, performance"; tree="Average CPU utilization?`n`n< 10% avg with spikes < 50% -> t4g (burstable, 30% savings)`n10-20% avg -> t4g possible but monitor credit balance`n> 20% avg -> m7g required (t4g will exhaust credits)`n`nSustained peak duration?`n< 30 minutes -> t4g burst credits cover peaks`n> 30 minutes -> m7g needed for sustained throughput`n`nEnvironment?`nDev/staging -> t4g (low utilization, credits accumulate)`nProduction -> m7g unless workload is truly burstable"; rationale="t4g instances earn CPU credits at 1 credit per vCPU hour. Sustained CPU above 20% depletes credits, throttling performance to baseline."; default="t4g for dev/staging; m7g for production; only use t4g in production if average CPU < 10%"; risk="t4g in production with sustained load causes CPU credit exhaustion, throttled performance, dropped requests."}
        }
        '^server-provisioning' {
            $trees += @{name="EBS Volume Type Selection"; context="Choose between gp3, gp2, io2, and instance store for Laravel server storage."; criteria="cost, performance"; tree="Workload type?`n`nWeb server -> gp3 (3000 IOPS baseline sufficient)`nDatabase server -> gp3 or io2 (if >16000 IOPS needed)`nCache/temp data -> Instance store (ephemeral, high perf)`n`nIOPS requirement?`n< 16000 IOPS -> gp3 (same price as gp2, 30x better baseline)`n> 16000 IOPS -> io2 (provisioned IOPS, higher cost)`n`nCurrently using gp2?`nYES -> Migrate to gp3 immediately (free upgrade, higher performance)`nNO -> Stay with gp3"; rationale="gp3 provides 3000 IOPS baseline at the same price as gp2's 100 IOPS/GB. For a 30GB volume, gp3 delivers 30x more IOPS at the same price."; default="gp3 for all volumes; io2 only for high-performance databases needing >16000 IOPS"; risk="Using gp2 instead of gp3 leaves 30x IOPS at same price. Using io2 for web servers adds unnecessary cost."}
            $trees += @{name="EBS Volume Right-Sizing"; context="Determine optimal EBS volume size from actual usage data."; criteria="cost"; tree="Current root volume usage?`n`n< 10GB -> 20GB root volume sufficient`n10-20GB -> Right-size during next maintenance`n> 20GB -> Investigate what consumes space`n`nData volume monitored for 30 days?`nYES -> Size at P95 usage + 20% headroom`nNO -> Start with 30GB, set CloudWatch alarm at 80%`n`nLog volume separate?`nYES -> 10-30GB for logs, alarm at 80%`nNO -> Split root and data volumes for isolation"; rationale="EBS costs $0.08/GB/month. 100GB unused costs $96/year per instance. Across 30 instances, that's $2,880/year in completely wasted storage spend."; default="Root: 20GB gp3; Data: 30GB starting, size based on 30-day monitoring; Logs: 10-30GB gp3"; risk="Over-provisioning every instance by 100GB costs thousands annually without any performance benefit."}
            $trees += @{name="Swap Configuration for PHP Workloads"; context="Determine whether and how much swap to configure on Laravel servers."; criteria="performance, reliability"; tree="Application type?`n`nPHP-FPM web server -> 2GB or 2x RAM (whichever higher)`nOctane server -> 2GB minimum`nQueue worker -> 2GB minimum`nDatabase server -> Follow DB engine swap guidelines`n`nAvailable RAM?`n< 2GB -> 2x RAM swap (critical for PHP memory safety)`n2-4GB -> 2GB swap`n> 4GB -> 2GB swap (RAM sufficient for most workloads)`n`nUsing instance store?`nYES -> Use instance store for swap (faster than EBS)`nNO -> Use EBS swap partition or swap file"; rationale="PHP memory leaks can OOM servers without swap. Swap provides buffer for graceful degradation instead of immediate OOM kills dropping all active requests."; default="2GB swap on all application servers; instance store if available; monitor swap usage for memory leak detection"; risk="No swap = OOM killer terminates PHP processes under memory pressure, causing 50x errors."}
        }
        '^php-fpm-tuning' {
            $trees += @{name="max_children Memory Calculation"; context="Calculate optimal PHP-FPM max_children based on server memory and worker footprint."; criteria="performance, cost"; tree="Total server RAM?`n`n2GB -> Reserve 0.5GB OS = ~40 children max`n4GB -> Reserve 1GB OS = ~70 children max`n8GB -> Reserve 1.5GB OS = ~150 children max`n16GB -> Reserve 2GB OS = ~310 children max`n`nAverage worker memory measured?`nYes -> Use actual value (Laravel: 30-80MB per worker)`nUnknown -> Default 45MB, adjust after monitoring`n`nCPU cores also a factor?`nChildren > 2x cores -> Cap at 2x cores (context switching degrades throughput)`nChildren <= 2x cores -> Memory-based calculation is correct"; rationale="Each Laravel PHP-FPM worker consumes 30-80MB. Setting max_children higher than available memory causes OOM kills. CPU-bound workloads get diminishing returns beyond 2x cores."; default="max_children = (RAM - OS_reserve) / avg_worker_memory; cap at 2x CPU cores"; risk="max_children too high causes OOM kills and 50x errors. Too low wastes CPU capacity."}
            $trees += @{name="pm.max_requests Configuration"; context="Set optimal max_requests to balance memory cleanup vs worker restart overhead."; criteria="performance, reliability"; tree="OPcache validate_timestamps enabled?`n`nNO (production) -> 500-1000 requests (memory cleanup focus)`nYES (development) -> 200-500 (fresher state)`n`nMemory leak rate?`nLow (< 1 KB/req) -> 1000-2000 requests`nMedium (1-10 KB/req) -> 500-1000 requests`nHigh (> 10 KB/req) -> 200-500 + fix leaks first`n`nTraffic volume?`nHigh (> 100 req/s) -> 1000 (fewer restarts, lower overhead)`nLow (< 10 req/s) -> 500 (restart overhead negligible)"; rationale="Laravel requests accumulate ~1KB memory per request. After 10K requests, a worker may use 2x baseline memory. max_requests restarts workers to release accumulated memory."; default="500-1000 for production; start at 1000, reduce if memory issues appear"; risk="No max_requests = unbounded memory growth, eventual OOM kills. Too low = constant restarts wasting CPU."}
            $trees += @{name="Dynamic vs Static vs On-Demand Pool Mode"; context="Choose PHP-FPM pool mode based on traffic pattern and server resources."; criteria="performance, cost"; tree="Traffic pattern?`n`nPredictable stable load -> Static pool`nVariable traffic -> Dynamic pool (most common)`nVery low or sporadic -> On-demand pool`n`nServer resources?`nMemory-constrained (< 2GB) -> On-demand (saves memory)`nAdequate RAM (4GB+) -> Dynamic (pre-spawned, no latency penalty)`n`nLatency sensitivity?`nHigh (user-facing API) -> Dynamic or Static`nLow (background) -> On-demand acceptable"; rationale="Static pool wastes memory during low traffic. Dynamic balances memory and latency. On-demand creates workers per request (50-200ms penalty) but saves memory."; default="Dynamic for most production; On-demand for low-traffic; Static for predictable high-traffic"; risk="On-demand for high-traffic adds 50-200ms latency per request. Static for variable load wastes 80% of workers."}
        }
        '^opcache-tuning' {
            $trees += @{name="OPcache Memory Allocation Sizing"; context="Determine opcache.memory_consumption for Laravel application codebase size."; criteria="performance"; tree="Application PHP file count?`n`n< 2000 files -> 64MB may suffice, use 128MB safe default`n2000-5000 files -> 128MB (standard Laravel + vendor)`n> 5000 files -> 256MB (large apps with many packages)`n`nCurrent OPcache hit rate?`n< 95% -> Increase memory (evictions occurring)`n95-99% -> Current allocation adequate`n> 99% -> No change needed`n`nVerified via opcache_status()?`nYES -> Adjust based on memory_usage metrics`nNO -> Run opcache_get_status() to check hit rate"; rationale="Insufficient OPcache memory causes entry eviction via LRU, forcing PHP recompilation on subsequent requests. 128MB covers most Laravel applications."; default="128MB for standard Laravel; 256MB for large applications; verify hit rate >99%"; risk="Insufficient memory causes 10-30% miss rate, wasting 50-70% CPU on recompilation."}
            $trees += @{name="validate_timestamps in Production"; context="Decide whether to disable OPcache file modification checking for production performance."; criteria="performance, security"; tree="Production environment?`n`nYES -> Disable validate_timestamps (opcache.validate_timestamps=0)`nNO (development) -> Keep enabled for code changes to reflect`n`nDeployment strategy?`nAtomic deploys (new files) -> validate_timestamps=0 safe`nIn-place updates -> Needs explicit cache clear`n`nCache clear mechanism?`nDeploy script includes opcache_reset() -> Safe to disable`nNo cache clear -> Keep enabled or add cache clear"; rationale="validate_timestamps causes stat() syscall on every PHP file every request. Disabling saves microseconds per file; across hundreds of Laravel files, this translates to 50-70% CPU reduction."; default="validate_timestamps=0 in production with deploy-time opcache_reset()"; risk="Enabling in production wastes CPU on stat() calls. Disabling without deploy cache clear serves stale code."}
            $trees += @{name="JIT Compilation Decision"; context="Determine whether to enable PHP JIT compilation based on workload type."; criteria="performance"; tree="Workload type?`n`nCPU-bound (image, PDF, calculations) -> Enable JIT (20-30% CPU improvement)`nI/O-bound (database, cache, HTTP) -> Minimal benefit`nMixed -> Enable if CPU-bound paths are significant`n`nPHP version?`nPHP 8.0+ -> JIT available`nPHP < 8.0 -> Upgrade PHP first`n`nRuntime?`nOctane (long-lived workers) -> JIT beneficial (amortized across millions of requests)`nPHP-FPM (per-request) -> JIT less impactful"; rationale="JIT compiles hot PHP functions to native machine code. For CPU-bound workloads, this provides 20-30% improvement. I/O-bound apps spend most time waiting on database/cache."; default="Enable JIT (mode=tracing, buffer=100M) for Octane CPU-bound tasks; skip for I/O-heavy PHP-FPM"; risk="Enabling JIT for purely I/O-bound apps adds complexity and memory overhead without meaningful improvement."}
        }
        '^octane-resource-usage' {
            $trees += @{name="Octane Worker Count Decision"; context="Determine optimal Octane worker count based on CPU cores and workload profile."; criteria="performance, cost"; tree="Number of CPU cores?`n`nSet base worker count = CPU cores`n`nWorkload profile?`nCPU-bound -> workers = CPU cores (no benefit beyond)`nI/O-heavy -> workers = 1.5-2x CPU cores (yield during waits)`nMixed -> workers = CPU cores + 1-2 for overhead`n`nMonitor context switching?`ncs/sec < 20000 per core -> OK`ncs/sec > 20000 per core -> Reduce workers`nRun queue > 2x cores -> Reduce workers"; rationale="CPU-bound workloads saturate cores; extra workers cause context switching that reduces throughput. I/O-heavy workers yield during waits, allowing more concurrent workers."; default="Workers = CPU cores for CPU-bound; +1-2 for I/O-heavy; monitor cs/sec and run queue"; risk="Too many workers causes extreme context switching where throughput drops below PHP-FPM levels."}
            $trees += @{name="Octane Memory Management"; context="Configure memory limits and restart policies for long-running Octane workers."; criteria="performance, reliability"; tree="Per-worker memory limit?`n`nSet memory_limit = 256M or 512M in php.ini/Octane config`n`nMemory growth pattern?`nStable at ceiling -> Worker health good`nGrowing unbounded -> Memory leak detected; set max_requests`n`nmax_requests setting?`nSet 1000-5000 depending on app`nWorkers restart after N requests, releasing accumulated memory`n`nOPcache + JIT enabled?`nEnabled -> 50-70% CPU reduction (OPcache) + 20-30% (JIT)`nDisabled -> Enable immediately for Octane"; rationale="Octane workers persist across thousands of requests, accumulating memory. max_requests provides restart-based memory reclamation. Without it, workers grow to memory_limit and get OOM killed."; default="memory_limit=256M, max_requests=2000, OPcache + JIT enabled"; risk="No max_requests = unbounded memory growth, OOM kills failing all in-flight requests."}
            $trees += @{name="Octane vs PHP-FPM Decision"; context="Choose between Octane and PHP-FPM based on traffic volume and app compatibility."; criteria="performance, cost, complexity"; tree="Current traffic volume?`n`n< 50 req/s -> PHP-FPM simpler; cost difference negligible`n50-500 req/s -> Octane provides 3-5x throughput improvement`n> 500 req/s -> Octane strongly recommended for cost-effective compute`n`nApp compatibility?`nSimple CRUD -> Octane works with minimal changes`nComplex packages -> Test all critical packages for compatibility`n`nGlobal state usage?`nStateless code -> Octane safe to deploy`nStatic properties -> Must refactor for Octane sandbox`n__destruct() cleanup -> Must refactor for persistent workers"; rationale="Octane eliminates per-request boot overhead (30-80ms), enabling 3-10x throughput on identical hardware. This reduces server count and compute costs by 50-80%."; default="Octane for all production > 100 req/s; PHP-FPM for low-traffic or incompatible apps"; risk="Deploying Octane without package compatibility testing causes data leakage across requests."}
        }
        '^roadrunner-binary' {
            $trees += @{name="RoadRunner vs Swoole for Octane"; context="Choose between RoadRunner (Go) and Swoole (PHP extension) as Octane server backend."; criteria="complexity, performance, deployment"; tree="Deployment environment?`n`nDocker containers -> RoadRunner (simpler, no PHP extension)`nSelf-managed server -> Either; RR simpler, Swoole slightly faster`nKubernetes -> RoadRunner (single binary, ~30MB image)`n`nTeam expertise?`nPHP-only team -> RoadRunner (no extension compilation)`nPHP extension experience -> Swoole acceptable`n`nPerformance requirement?`nMaximum throughput -> Swoole 5-10% faster for CPU-bound`nStandard -> RoadRunner sufficient (2000+ req/s)`nDebugging simplicity -> RoadRunner (Go binary)"; rationale="RoadRunner is a static Go binary with no PHP extension dependencies, simplifying Docker builds. Swoole requires pecl install and extension loading but offers slightly higher throughput."; default="RoadRunner for most deployments; Swoole only if maximum throughput critical with extension expertise"; risk="Swoole extension conflicts cause crashes after N requests. Missing RR health check causes total downtime."}
            $trees += @{name="RoadRunner Worker Pool Configuration"; context="Configure worker pool size and restart thresholds in .rr.yaml."; criteria="performance, reliability"; tree="CPU cores available?`n`nSet num_workers = CPU cores (CPU-bound)`nSet num_workers = 1.5-2x cores (I/O-heavy)`n`nmax_jobs setting?`nSet 500-1000 to prevent memory leaks`nWorkers restart after N requests, releasing memory`n`nmax_memory per worker?`nSet 128MB restart threshold`nMonitor actual memory; adjust if workers restart too frequently`n`nStatic files served directly?`nEnable static plugin in .rr.yaml for direct asset serving`nNo need for separate Nginx reverse proxy layer"; rationale="max_jobs and max_memory provide two independent safety mechanisms against memory leaks. Workers restart after either threshold is hit, ensuring stable long-term operation."; default="num_workers = CPU cores, max_jobs = 500, max_memory = 128MB, enable static plugin"; risk="No max_jobs = unbounded memory growth. Over-allocating workers causes CPU thrashing."}
            $trees += @{name="RoadRunner Deployment Architecture"; context="Design deployment with single-process container model."; criteria="complexity, performance"; tree="Static assets strategy?`n`nSingle process -> Use RR static plugin (no Nginx needed)`nSeparate CDN -> CloudFront/S3 for assets, RR for API`n`nContainer image size?`nConcern -> RR single binary ~30MB vs 200MB Nginx+FPM image`nNo concern -> Either approach works`n`nProcess management?`nDocker -> RR as ENTRYPOINT, health check on /health`nKubernetes -> Single container with liveness probes`nSystemd -> RR service with auto-restart`n`nPort configuration?`nExpose 8080 (RR default), ALB targets this port`nNo need for port 80/443 internally (terminated at ALB)"; rationale="RoadRunner serves HTTP and static files directly, eliminating the Nginx reverse proxy layer. This reduces deployment complexity, container image size, and operational surface area."; default="Single Docker container with rr serve entrypoint, static plugin, health check endpoint"; risk="Adding unnecessary Nginx in front of RR adds complexity. No process manager = single point of failure."}
        }
        '^worker-pool-sizing' {
            $trees += @{name="Worker Count by Bottleneck Identification"; context="Determine optimal worker count based on CPU, memory, or I/O bottleneck."; criteria="performance, cost"; tree="Identify primary bottleneck?`n`nCPU-bound (intensive computation) -> workers = CPU cores`nMemory-bound (limited RAM) -> workers = Available RAM / worker_memory`nI/O-bound (DB, API, cache) -> workers = 2-4x CPU cores`n`nMemory per worker estimated?`n< 50MB -> Memory constrained; reduce workers`n50-150MB -> Normal range for Laravel workers`n> 150MB -> I/O bound or over-provisioned`n`nMonitor idle worker %?`n0% idle at peak -> Under-provisioned; add workers`n10-20% idle -> Optimal range`n> 50% idle -> Over-provisioned; reduce workers"; rationale="Sizing for the wrong bottleneck wastes resources. CPU-bound: workers beyond cores cause context switching. Memory-bound: too many workers cause OOM. I/O-bound: more workers can run concurrently."; default="CPU-bound: workers=cores; I/O-bound: 2-3x cores; Memory-bound: calculate from RAM"; risk="Oversubscribed workers cause OOM and context switching thrashing. Undersubscribed workers waste capacity."}
            $trees += @{name="Separate Worker Pools Design"; context="Design separate worker pools for web, queue, and scheduled task workloads."; criteria="performance, reliability"; tree="Workload types on server?`n`nWeb only -> Single pool for PHP-FPM or Octane workers`nWeb + queue -> Separate pools; dedicated servers preferred`nMultiple queue priorities -> Separate pools per priority`n`nQueue priority needed?`nYES -> High pool (more workers, lower latency) + Low pool (fewer workers)`nNO -> Single queue pool with uniform worker count`n`nServer dedicated to single workload?`nYES -> Optimal; size pool for that workload only`nNO -> Use cgroups to allocate CPU shares per pool"; rationale="A large queue job should never block web request processing. Separate pools ensure each workload gets appropriate capacity without interference."; default="Dedicated servers for web and queue; separate pools per priority with different worker counts"; risk="Shared pool causes queue jobs to degrade web response times by 30-50% during batch processing."}
            $trees += @{name="Queue Worker Throughput Sizing"; context="Calculate required queue workers from job throughput and duration."; criteria="performance, cost"; tree="Job throughput required (jobs/hour)?`n`nMeasure desired_jobs_per_hour from requirements`n`nAverage job duration (seconds)?`nMeasure avg_job_duration via Horizon/Telescope`n`nFormula: workers = ceil(desired_throughput / (3600 / avg_job_duration))`nExample: 500 jobs/hour at 3s avg job = ceil(500 / 1200) = 1 worker`n`nAdd buffer for spikes?`nYES -> 20-30% above calculated peak`nNO -> Risk of queue backlog during load spikes"; rationale="Worker count should be derived from throughput requirements and job duration, not guesswork. Each worker processes (3600 / avg_job_duration) jobs per hour."; default="Calculate from throughput + duration; add 20-30% buffer above estimated peak"; risk="Under-provisioning creates hours of backlog. Over-provisioning wastes memory on idle workers."}
        }
        '^context-switching' {
            $trees += @{name="Web and Queue Server Separation"; context="Decide whether to run queue workers on web servers or use dedicated instances."; criteria="performance, cost"; tree="Current architecture?`n`nWeb + queue on same -> Evaluate separation`nWeb and queue separate -> Already optimal`n`nServer CPU utilization?`n< 50% at peak -> Co-locate with cgroups limits`n50-80% -> Separate servers recommended`n> 80% -> Immediate separation required`n`nTraffic volume?`n< 50 req/s -> Co-location with cgroups acceptable`n50-200 req/s -> Separate servers recommended`n> 200 req/s -> Separate servers mandatory`n`nCost vs performance priority?`nCost savings -> Co-locate with cgroups CPU limits`nPerformance -> Dedicated servers"; rationale="Queue workers cause 10,000+ extra context switches per second, stealing 30-50% CPU from customer-facing web requests. Separation eliminates this contention."; default="Separate servers for web and queue; cgroups only for low-traffic apps under 50 req/s"; risk="Co-location causes 30-50% web response time degradation and confusing troubleshooting."}
            $trees += @{name="Worker Count to CPU Core Ratio"; context="Set optimal worker-to-CPU ratio to minimize context switching overhead."; criteria="performance"; tree="Workload type?`n`nCPU-bound -> Workers = 1-2x CPU cores`nI/O-bound -> Workers = 2-4x CPU cores`n`nCurrent vmstat cs/sec?`n< 10,000 cs/sec per core -> Healthy`n10,000-20,000 -> Monitor`n> 20,000 per core -> Too many workers; reduce 25%`n`nRun queue length?`n< 2x cores -> Appropriate`n> 2x cores -> Workers over-allocated; reduce`n`nThroughput before vs after reduction?`nIncreased -> Context switching was bottleneck`nDecreased -> Original count was needed"; rationale="Each worker beyond CPU cores causes 100+ involuntary context switches/second. Beyond 2x cores, throughput decreases due to switching overhead."; default="CPU-bound: workers=cores; I/O-bound: 2-3x cores; target cs/sec < 20,000 per core"; risk="Over-allocating workers wastes 20-50% of CPU on context switching, reducing effective capacity."}
            $trees += @{name="CPU Priority for Mixed Workloads"; context="Configure CPU priority via cgroups or nice on shared servers."; criteria="performance, reliability"; tree="Mixed workloads on same server?`n`nYES -> Configure cgroups or nice values`nNO -> No CPU priority needed on dedicated servers`n`ncgroups available?`nYES -> Set CPU shares: web=512, queue=256 (2:1 priority)`nNO -> Use nice: web=0, queue=10`n`nOctane workers present?`nYES -> CPU-pin to dedicated cores via taskset`nNO -> Standard scheduling sufficient`n`nMemory cgroups also configured?`nYES -> Prevents queue workers consuming all RAM`nNO -> Configure memory limits for queue cgroup"; rationale="cgroups ensure web workers get CPU priority during traffic spikes. CPU pinning eliminates cache misses from workers migrating between cores, providing ~5-10% throughput improvement."; default="cgroups CPU shares (web=512, queue=256); Octane workers CPU-pinned"; risk="No CPU limits on shared servers = queue jobs steal CPU from web during spikes."}
        }
        '^database-connection-pool' {
            $trees += @{name="Connection Pooler Selection (RDS Proxy vs PgBouncer)"; context="Choose pooler based on database engine and operational capacity."; criteria="cost, performance, maintenance"; tree="Database engine?`n`nMySQL/Aurora -> RDS Proxy ($15-30/month, managed, IAM auth)`nPostgreSQL -> PgBouncer (free, t4g.nano ~$5/month)`n`nOperational capacity?`nFully managed -> RDS Proxy (zero maintenance)`nCost-sensitive -> PgBouncer ($5 vs $15-30/month)`n`nIAM authentication needed?`nYES -> RDS Proxy (native IAM, 15-min credentials)`nNO -> Either works`n`nConnection count?`n< 100 -> Pooler may not be needed if max_connections sufficient`n> 100 -> Pooler definitely required"; rationale="RDS Proxy is fully managed ($15-30/month) but MySQL/Aurora-only. PgBouncer is free but needs a t4g.nano instance ($5/month) and is PostgreSQL-only."; default="RDS Proxy for Aurora/MySQL; PgBouncer for PostgreSQL"; risk="No pooler with >100 PHP-FPM workers causes 'too many connections' errors during traffic spikes."}
            $trees += @{name="Connection Pool Size Configuration"; context="Set optimal pool size based on database vCPUs and workload."; criteria="performance, cost"; tree="Database vCPU count?`n`n2 vCPU -> Pool size = 4-6 (2-3x vCPUs)`n4 vCPU -> Pool size = 8-12`n8 vCPU -> Pool size = 16-24`n`nPool mode (PgBouncer)?`nApp uses SET/temp tables -> Session pooling`nNo session state -> Transaction pooling (efficient)`n`nRead/write splitting?`nYES -> Writer pool = 2-3x vCPUs, Reader pool = 4-6x vCPUs`nNO -> Single pool size = 2-3x vCPUs`n`nMonitoring?`nAlarm at 80% pool capacity`nInvestigate sustained 90%+ utilization"; rationale="Database processes connections with ~2x vCPU overhead. More connections than this causes DB context switching. Fewer wastes slots."; default="Pool size = 2-3x DB vCPUs; transaction pooling for PostgreSQL; alarm at 80%"; risk="Pool too large overwhelms DB. Pool too small causes request queuing at the pooler."}
            $trees += @{name="Pool Utilization Monitoring Strategy"; context="Set up monitoring thresholds for connection pool health."; criteria="reliability, performance"; tree="Pool utilization metric available?`n`nYES -> Set alarm at 80% capacity`nNO -> Enable CloudWatch or PgBouncer metrics first`n`nAlert triggered (80%)?`nConsistently near 80% -> Right-size pool`nSporadic spikes -> Evaluate pool sizing`n`nCritical threshold (95%+)?`nScale out database or increase pool capacity`nCheck for connection leak in application`n`nRecovery documented?`nPool flush procedure for emergencies`nApplication retry logic for connection failures"; rationale="Connection pool exhaustion happens silently. Monitoring reveals sizing issues early before traffic spikes exhaust capacity."; default="CloudWatch alarm at 80% pool utilization with 5-minute evaluation period"; risk="No monitoring = silent request queuing, growing latency, timeout errors with no warning."}
        }
        '^fargate-pricing-analysis' {
            $trees += @{name="Fargate vs EC2 Platform Decision"; context="Choose between Fargate and EC2 for Laravel container workloads."; criteria="cost, operational_overhead"; tree="Team DevOps capacity?`n`n< 5 engineers -> Fargate (zero server management)`n5-10 engineers -> Either; Fargate preferred for velocity`n> 10 engineers -> EC2 feasible with ops team`n`nTask count?`n< 50 tasks -> Fargate (premium worth it)`n> 50 tasks -> EC2 20-40% cheaper`n`nWorkload predictability?`nVariable -> Fargate (auto-scaling, no planning)`nPredictable -> EC2 with RIs (20-40% cheaper)`n`nNeed SSH or custom AMIs?`nYES -> EC2 required`nNO -> Fargate sufficient"; rationale="Fargate carries a 20-40% premium over EC2 for zero server management. Worth it for teams < 5 engineers or < 50 tasks."; default="Fargate for teams < 5 engineers or < 50 tasks; EC2 for max cost optimization at scale"; risk="Fargate at scale pays 20-40% premium. EC2 with small teams creates ops burden."}
            $trees += @{name="Fargate Task Right-Sizing"; context="Right-size Fargate task CPU and memory to actual utilization."; criteria="cost, performance"; tree="Actual utilization monitored?`n`nYES -> Size at P95 + 20% headroom`nNO -> Start 1 vCPU/2GB, monitor 1 week`n`nActual memory vs allocation?`n< 60% allocated -> Reduce (charges for allocated, not used)`n60-80% -> Appropriate sizing`n> 80% -> Increase to prevent OOM`n`nARM vs x86?`nARM available -> Use Graviton (20% cheaper)`nx86 required -> Native binary dependencies`n`nEphemeral storage?`n< 20GB -> Free per task`n> 20GB -> Additional $0.000111/GB-hour"; rationale="Fargate charges for allocated memory, not used memory. Over-allocating by 2x wastes 50% of memory cost."; default="Start 1vCPU/2GB ARM; monitor 1 week; right-size to P95 + 20% headroom"; risk="Over-allocating memory costs 2x more. Under-allocating causes OOM kills."}
            $trees += @{name="ECS vs EKS Control Plane Selection"; context="Choose between free ECS and $73/month EKS control planes."; criteria="cost, complexity"; tree="Kubernetes expertise?`n`nExperienced -> EKS viable ($73/month)`nNot experienced -> ECS (simpler, free)`n`nMulti-service architecture?`n< 5 services -> ECS sufficient`nMany + complex routing -> EKS may help`n`nCost sensitivity?`nHIGH -> ECS (free vs $73/month adds 100%+ to small deployments)`nLOW -> Either; EKS provides portability`n`nPortability needed?`nMulti-cloud -> EKS (standard K8s, portable)`nAWS-only -> ECS (simpler, integrated, free)"; rationale="ECS is free; EKS costs $73/month per cluster. For most Laravel apps with 1-5 services, ECS provides equivalent functionality at zero cost."; default="ECS for most Laravel deployments; EKS only for K8s-experienced teams with multi-cloud needs"; risk="Paying $73/month EKS for a single service that ECS manages for free doubles infrastructure cost."}
        }
        '^fargate-spot-workers' {
            $trees += @{name="Spot vs On-Demand Worker Mix"; context="Determine optimal Spot and On-Demand capacity mix for queue workers."; criteria="cost, reliability"; tree="Worker characteristics?`n`nStateless, interruptible -> High Spot (70-90%)`nStateful, critical -> Higher On-Demand (50-100%)`n`nProcessing SLA?`nBest-effort hours -> 100% Spot (maximum savings)`nTimely minutes -> 70% Spot + 30% On-Demand`nCritical seconds -> 100% On-Demand`n`nSpot interruption tolerance?`nJobs checkpoint -> High Spot OK`nNo checkpoint -> Lower Spot percentage`n`nMulti-AZ?`n3 AZs -> Lower risk (diversified)`nSingle AZ -> Higher risk; increase On-Demand"; rationale="Spot offers up to 70% discount. Mixed capacity (70/30) ensures baseline throughput during Spot shortages."; default="70% Spot + 30% On-Demand for queue workers; 100% Spot for batch with checkpoints"; risk="100% Spot without fallback = queue stops during Spot shortage."}
            $trees += @{name="Graceful Shutdown for Spot Interruption"; context="Handle 2-minute SIGTERM warning for Spot capacity reclamation."; criteria="reliability"; tree="SIGTERM handler implemented?`n`nYES -> Supervisor catches signal for graceful shutdown`nNO -> Implement immediately before deploying Spot`n`nWorker timeout?`n--timeout=90 on Horizon (fits within 2-minute warning)`nJobs > 120 seconds get interrupted mid-execution`n`nIn-flight job handling?`nJobs < 90s -> Finish before termination`nJobs > 90s -> Implement checkpointing in DB`n`nSQS visibility timeout?`nSet to max_job_duration x 2`nEnsures interrupted jobs become visible for retry"; rationale="AWS sends SIGTERM 2 minutes before reclaiming Spot. Graceful handling allows in-flight jobs to complete or checkpoint."; default="--timeout=90 on Horizon; SIGTERM handler; checkpoint jobs > 2 minutes"; risk="No graceful shutdown = jobs terminated mid-execution, invisible retries, wasted processing."}
            $trees += @{name="Spot Instance Type Diversification"; context="Reduce interruption risk by diversifying instance types and AZs."; criteria="reliability, cost"; tree="Single instance type?`n`nYES -> Add similar types for diversification`nNO -> Already diversified`n`nInstance families?`nt4g + m7g (ARM) -> Good base diversification`nc7g + r7g -> Add compute/memory optimized`n`nAZ distribution?`nSingle AZ -> HIGH RISK; distribute across 3 AZs`n3 AZs -> Low risk; continue monitoring`n`nInterruption rate?`n> 15% weekly -> Diversify more or raise On-Demand`n< 10% weekly -> Current strategy effective"; rationale="Spot capacity varies by instance type and AZ. Diversification across types and AZs reduces interruption rate by 40-60%."; default="3+ instance types across 3 AZs; monitor SpotInterruptionCount weekly"; risk="Single type in one AZ = all workers interrupted simultaneously during capacity event."}
        }
        '^graviton-price-performance' {
            $trees += @{name="Graviton Migration Decision"; context="Decide whether to migrate x86 workloads to Graviton/ARM."; criteria="cost, risk"; tree="New or existing?`n`nNEW -> Use Graviton (20% cheaper, zero effort)`nEXISTING -> Evaluate migration`n`nPHP version?`nPHP 8.0+ -> Full ARM support; migrate safely`nPHP < 8.0 -> Upgrade PHP first`n`nNative x86 dependencies?`nNone -> Migrate staging first, then production`nSome -> Test each on ARM`n`nCI/CD ready?`nProduces ARM images -> Ready to migrate`nx86 only -> Add multi-arch buildx first"; rationale="Graviton offers 20-34% cost reduction at identical PHP performance. PHP 8.0+ has first-class ARM support. 90%+ of Laravel apps migrate with zero code changes."; default="Use Graviton for all new deployments; migrate existing with staging validation first"; risk="Not migrating leaves 20-34% savings unclaimed. Migrating without testing native deps causes failures."}
            $trees += @{name="Graviton Service Coverage"; context="Identify which AWS services to migrate for maximum savings."; criteria="cost"; tree="Compute services?`n`nEC2 -> t4g/m7g/r7g/c7g (20% cheaper)`nFargate -> ARM Fargate (20% cheaper)`nLambda -> ARM (34% cheaper duration)`n`nDatabase services?`nRDS -> db.r7g (20% cheaper)`nAurora -> Graviton-compatible instances`n`nCache services?`nElastiCache -> cache.r7g (20% cheaper)`n`nMigration order?`nFirst -> Compute (EC2/Fargate/Lambda) for immediate savings`nSecond -> RDS for additional 20%`nThird -> ElastiCache for remaining 20%"; rationale="Graviton savings compound across all AWS compute services. Migrating EC2 + RDS + ElastiCache can reduce total infrastructure cost by 20-25%."; default="Migrate compute first, then database, then cache; target uniform ARM architecture"; risk="Migrating compute but not RDS/ElastiCache misses 20% additional savings on each."}
            $trees += @{name="Multi-Architecture Build Strategy"; context="Implement multi-arch Docker builds for safe Graviton migration with rollback."; criteria="reliability, operational_overhead"; tree="Docker images used?`n`nYES -> Implement multi-arch buildx`nNO -> Select ARM instance types in templates`n`nCI/CD capability?`nMulti-arch capable -> Add buildx, manifest lists`nLimited -> Single-arch ARM with manual x86 fallback`n`nRollback needed?`nMulti-arch images -> Instant by switching instance type`nSingle-arch -> Need pipeline rebuild`n`nProduction cutover?`nGradual (10%-50%-100%) -> Low risk`nAll-at-once -> Higher risk; have rollback plan"; rationale="Multi-arch Docker images enable deployment to both ARM and x86, providing instant rollback safety."; default="Multi-arch Docker builds via buildx + gradual traffic shift to Graviton"; risk="Single-arch ARM images without rollback = extended downtime if compatibility issues."}
        }
        '^lambda-pricing-breakdown' {
            $trees += @{name="Lambda Memory Right-Sizing"; context="Find cost-optimal Lambda memory allocation for each function."; criteria="cost, performance"; tree="Test at multiple memory levels:`n`n128MB -> Cheapest per-second, slowest`n256MB -> Good for simple API functions`n512MB -> Standard for Laravel/Bref`n1024MB -> Faster, double per-second cost`n`nCalculate cost per invocation:`ncost = (mem_GB x duration_s x $0.0000166667) + $0.0000002`n`nPick cheapest meeting SLA?`nYES -> Cost-optimal selected`nNO -> Paying more than needed`n`nARM enabled?`nYES -> ~34% lower duration cost`nNO -> Enable ARM for immediate savings"; rationale="Higher memory costs more per second but may reduce duration. The cost-optimal point is rarely the lowest or highest memory setting."; default="256MB for simple functions, 512MB for Laravel/Bref; test and compute cost per invocation"; risk="Over-allocating to 1024MB for simple functions costs 4x more with no duration benefit."}
            $trees += @{name="Lambda vs Fargate Compute Model"; context="Choose between Lambda and Fargate based on workload volume and duration."; criteria="cost, performance"; tree="Monthly request volume?`n`n< 5M req/month -> Lambda (scale-to-zero)`n5-30M req/month -> Model both (breakeven zone)`n> 30M req/month -> Fargate cheaper (256MB/500ms)`n`nExecution duration?`n< 100ms -> Lambda efficient`n100-500ms -> Standard breakeven range`n> 1s -> Lambda expensive; prefer Fargate`n`nTraffic pattern?`nSpiky with idle -> Lambda (scale-to-zero)`nSteady 24/7 -> Fargate (flat-rate wins)`n`nCold starts OK?`nYES -> Lambda without Provisioned Concurrency`nNO -> +PC adds cost; may push to EC2"; rationale="Lambda's scale-to-zero eliminates idle compute cost. For steady traffic, Fargate's flat-rate pricing is 30-60% cheaper."; default="Lambda for <5M req/month; Fargate for 5-50M; EC2 for >50M"; risk="Lambda for steady high-volume costs 2-3x more than Fargate."}
            $trees += @{name="Provisioned Concurrency Decision"; context="Determine if Provisioned Concurrency is cost-justified vs EC2."; criteria="cost, performance"; tree="Cold start acceptable?`n`nYES (>200ms) -> No PC needed`nNO (<100ms) -> Evaluate PC`n`nConsistent traffic baseline?`nYES -> PC may be cost-effective`nNO -> PC charges for idle capacity`n`nCost comparison:`n10 provisioned 1GB functions = ~$50/month`n1 t4g.small EC2 = ~$17/month (always-on)`n`nIf PC cost > EC2?`nYES -> Use EC2/Fargate instead`nNO -> PC acceptable"; rationale="Provisioned Concurrency charges even when not invoked. $50/month can buy a t4g.small running 24/7."; default="Avoid PC as default; use EC2/Fargate if consistent sub-100ms latency required"; risk="Enabling PC adds $50+/month baseline that may exceed EC2 alternative."}
        }
        '^lambda-ec2-breakeven' {
            $trees += @{name="Breakeven Point Calculation"; context="Calculate Lambda vs EC2 breakeven for your specific workload metrics."; criteria="cost"; tree="Gather 30-day metrics:`n`nMonthly request count`nAvg memory per function (MB)`nAvg execution duration (ms)`n`nCalculate Lambda cost:`nrequests x $0.0000002 + (requests x mem_GB x duration_h x $0.0000166667)`n`nCalculate EC2 cost:`ninstances_needed x instance_rate x 730 hours`n`nCompare:`nLambda cheaper -> Use Lambda (below breakeven)`nEC2 cheaper -> Use EC2/Fargate (above breakeven)`nSimilar -> Fargate as middle ground"; rationale="Breakeven shifts dramatically with memory and duration. 512MB/1s function breakeven is ~7.5M requests, not 30M. Model with your actual metrics."; default="Model with 30-day actual metrics; re-evaluate quarterly"; risk="Using reference profile instead of actual gives breakeven wrong by 2-4x."}
            $trees += @{name="Hidden Cost Factor Inclusion"; context="Include VPC, PC, and ops overhead in Lambda vs EC2 comparison."; criteria="cost"; tree="Lambda in VPC?`n`nYES -> Add NAT Gateway ($32/month + $0.045/GB)`nNO -> No networking cost`n`nPC needed?`nYES -> Add PC cost to Lambda`nNO -> No PC baseline`n`nOps overhead?`nEC2: 5-10 hours/month ($500-1000 value)`nFargate: Reduced overhead`nLambda: Zero operations`n`nSavings Plans?`nFactor 17% Lambda discount or up to 66% EC2 discount`nNo commitment -> Use on-demand pricing"; rationale="TCO includes hidden costs shifting breakeven by 20-50%. VPC networking alone adds $50-200/month to Lambda."; default="Include all hidden costs + ops overhead in TCO comparison"; risk="Comparing only compute line items underestimates Lambda true cost by 20-50%."}
            $trees += @{name="Hybrid Lambda + EC2 Architecture"; context="Design hybrid using EC2 baseline + Lambda overflow."; criteria="cost, performance, complexity"; tree="Baseline steady?`n`nYES -> EC2 baseline (RIs for discount)`nNO -> Lambda for all (scale-to-zero)`n`nSpikes significant (>2x)?`nYES -> Lambda handles overflow (no idle capacity)`nNO -> EC2 alone with Auto Scaling`n`nComplexity acceptable?`nYES -> Hybrid: EC2 + Lambda overflow`nNO -> Single platform simpler`n`nMonthly compute spend?`n> $5K -> Hybrid complexity may be worth it`n< $5K -> Single platform simpler"; rationale="Hybrid uses EC2 for steady baseline and Lambda for spikes. Most cost-efficient but operationally complex."; default="Single platform (Fargate) for most apps < $5K/month; hybrid only for clear baseline/spike separation"; risk="Hybrid complexity often negates savings under $5K/month."}
        }
        '^laravel-cloud-vs-vapor' {
            $trees += @{name="Cloud vs Vapor Platform Selection"; context="Choose between Laravel Cloud (Fargate) and Vapor (Lambda)."; criteria="cost, performance, complexity"; tree="Monthly request volume?`n`n< 100K req/day -> Cloud Starter ($5/month)`n100K-5M req/day -> Cloud (cost predictability)`n> 5M req/day -> Cloud or Forge+EC2`n`nCurrent platform?`nNew project -> Cloud (default 2026)`nVapor > $1K/month -> Model migration for 30-50% savings`nVapor < $500/month -> Stay (migration cost > savings)`n`nOctane compatible?`nTested -> Cloud (Octane default, 3-10x throughput)`nNot tested -> Test first; Cloud savings depend on it`nIncompatible -> Fix packages or stay`n`nCold start sensitivity?`nLow -> Auto-hibernation fine`nHigh -> Need min containers (reduces savings)"; rationale="Real-world migrations show 30-50% savings Vapor to Cloud. Vapor's 9x multiplier makes it uneconomical above 20M req/month."; default="Cloud for new projects and Vapor migrations > $1K/month; test Octane first"; risk="Migrating without Octane validation = failed migration or reduced savings."}
            $trees += @{name="Vapor True Cost with Multiplier"; context="Calculate Vapor's true cost including Lambda invocation multiplier."; criteria="cost"; tree="Measure multiplier?`n`nDivide Lambda invocations by HTTP requests`nAverage: 9x; Range 4-15x`n`nApply to calculation:`nEffective cost/req = raw Lambda x multiplier`n$0.00000228/req x 9x = $0.0000205/req`n`nCompare to alternatives:`nCloud: ~$0.000004/req (5x cheaper)`nBref: $0.00000228/req (1x, no multiplier)`n`nAdd hidden Vapor costs?`nAPI Gateway, CloudFront, NAT Gateway, deployment hooks"; rationale="A single HTTP request on Vapor triggers 9+ Lambda invocations. This multiplier makes Vapor 3-5x more expensive than raw Lambda suggests."; default="Always factor multiplier into Vapor cost; measure actual from Vapor bill"; risk="Comparing Cloud to raw Lambda (without multiplier) makes Vapor appear 3-5x cheaper than reality."}
            $trees += @{name="Vapor to Cloud Migration Decision"; context="Determine when to migrate from Vapor to Cloud."; criteria="cost, risk"; tree="Current Vapor spend?`n`n< $500/month -> Migration not worth effort`n$500-$2K -> Model; payback 6-12 months`n$2K-$10K -> Strong candidate; payback 3-6 months`n> $10K -> Urgent; migrate ASAP`n`nReadiness checklist:`nOctane validated? Cloud account ready? Rollback prepared?`n`nApproach:`nPhased (staging -> prod) -> Lower risk`nRip-and-replace -> Higher risk`n`nPost-migration:`nMonitor cost vs baseline 30 days`nRight-size containers after 2 weeks`nTune auto-scaling"; rationale="Migration payback typically 3-6 months for apps > $1K/month Vapor. Risk low with rollback option."; default="Validate Octane; migrate staging; 48h monitor; production with 2-week Vapor rollback"; risk="Rip-and-replace with no rollback = extended downtime if issues arise."}
        }
        '^laravel-octane-throughput' {
            $trees += @{name="Octane Adoption Decision"; context="Decide whether to adopt Octane based on traffic and app profile."; criteria="performance, cost, complexity"; tree="Current traffic?`n`n< 100K req/day -> PHP-FPM sufficient`n100K-1M req/day -> Octane strongly recommended`n> 1M req/day -> Octane mandatory`n`nApp type?`nCPU-bound -> 7-10x throughput gain`nI/O-bound -> 3-5x throughput gain`n`nCompatibility?`nAll packages tested -> Proceed`nSome untested -> Test all critical packages`nIncompatible -> Refactor or find alternatives`n`nBackend selection?`nFrankenPHP -> Default (Docker-native)`nSwoole -> Maximum throughput`nRoadRunner -> Simplest debugging"; rationale="Octane delivers 3-10x throughput over PHP-FPM on identical hardware, reducing server count by 50-80%."; default="Enable Octane for all production > 100K req/day; FrankenPHP for new deployments"; risk="Not using Octane leaves 50-80% cost savings on the table."}
            $trees += @{name="Octane Worker and Memory Configuration"; context="Configure worker count, max_requests, and memory limits."; criteria="performance, reliability"; tree="CPU cores?`n`nCPU-bound -> workers = cores`nI/O-heavy -> workers = 1.5-2x cores`n`nmax_requests?`nSet 1000-5000 (prevents unbounded memory growth)`n`nMemory limit?`n256M or 512M per worker`nMonitor > 10KB/req growth = memory leak`n`nJIT enabled?`nFor CPU-bound tasks: mode=tracing, buffer=100M`nFor I/O-bound: minimal benefit"; rationale="CPU-bound workers saturate cores. max_requests prevents memory leak accumulation. JIT compiles hot functions to native code."; default="Workers = CPU cores + 1; max_requests = 2000; memory = 256M; JIT for CPU-bound"; risk="Too many workers = CPU thrashing. No max_requests = OOM kills."}
            $trees += @{name="Octane Package Compatibility Audit"; context="Audit packages for Octane compatibility before migration."; criteria="reliability, performance"; tree="Critical packages identified?`n`nYES -> List all; categorize by risk`nNO -> Run composer show -i`n`nStatic/global state?`nStatic properties -> Must be stateless or reset per-request`nSingletons -> Must be request-scoped safe`nService providers -> Must be Octane-compatible`n`nDestructors?`n__destruct() cleanup -> Won't fire; must refactor`nShutdown functions -> Register via Octane lifecycle hooks`n`nLoad test:`nRun 10K+ test requests before production`nMonitor for data leakage, memory growth, errors`nCompare to PHP-FPM baseline"; rationale="Octane keeps state across requests. Packages assuming per-request lifecycle break silently, causing data leakage."; default="Test all critical packages with Octane for 10K+ requests before production cutover"; risk="Untested packages cause data leakage across users or silent failures in production."}
        }
        '^performance-vs-cost' {
            $trees += @{name="Optimization Prioritization (80/20 Rule)"; context="Identify highest-ROI performance optimizations first."; criteria="cost, performance"; tree="Profile before optimizing?`n`nYES -> Identify biggest bottleneck`nNO -> Profile first (90% of guesses wrong)`n`nIssue type found?`nMissing OPcache -> 5 min change, 50-70% CPU reduction`nPHP-FPM misconfig -> Config change, 10-30% improvement`nMissing DB index -> Add index, 100x speedup`nN+1 queries -> Fix eager loading`n`nROI estimate:`n5 min to implement, $500/month savings -> DO IT`n40 hours to implement, $100/month savings -> SKIP`n`nOrder: OPcache -> FPM -> DB indexes -> Queries -> Octane"; rationale="80% of optimization benefit from 20% of changes. OPcache alone gives 50-70% CPU reduction for one config change."; default="Profile first; implement highest ROI first (OPcache -> FPM -> indexes -> queries -> Octane)"; risk="Optimizing before measuring = 90% chance of fixing the wrong thing."}
            $trees += @{name="Compute Platform Breakeven"; context="Find cost-optimal platform (Lambda/Fargate/EC2) for workload."; criteria="cost, performance"; tree="Request volume?`n`n< 100 req/s -> Lambda (scale-to-zero)`n100-1000 req/s -> Fargate (balanced)`n> 1000 req/s -> EC2 (max price-performance)`n`nDuration per request?`n< 100ms -> Lambda efficient`n100-500ms -> Standard; breakeven analysis needed`n> 500ms -> Fargate/EC2 cheaper`n`nTraffic pattern?`nSteady -> EC2 with RIs (up to 66% off)`nVariable -> Fargate with auto-scaling`nSpiky -> Lambda (scale-to-zero)`n`nOps overhead?`nLambda: $0; Fargate: minimal; EC2: 5-10 hrs/month ($500-1000)"; rationale="Each platform dominates a specific traffic range. Lambda at low volume, EC2 at high volume, Fargate in the middle."; default="Lambda < 100 req/s; Fargate 100-1000; EC2 > 1000 with RIs"; risk="Lambda at 1000+ req/s costs 2-3x more than EC2. EC2 for 10 req/s wastes 90% of capacity."}
            $trees += @{name="Cost-Performance Budgets"; context="Set performance budgets and cost-per-request targets."; criteria="cost, performance"; tree="Cost per request?`n`nTarget < $0.0001/request for most Laravel apps`nTrack monthly: total compute / total requests`nTrending up = degradation; investigate`n`nLatency budgets?`np50 < 200ms, p95 < 500ms, p99 < 1000ms`n`nCI/CD gates?`nYES -> Enforce budgets in pipeline`nNO -> Add performance gates`n`nCost vs latency tradeoff?`n10% more latency for 30% cost reduction -> Acceptable`n10% latency improvement for 2x cost -> Only if latency impacts revenue"; rationale="Cost per request provides a single health metric. Target < $0.0001/request gives a baseline for optimization decisions."; default="Target < $0.0001/request, p50 < 200ms, p95 < 500ms; review monthly"; risk="No budgets = degradation undetected until users complain or finance flags the bill."}
        }
        '^queue-worker-scaling' {
            $trees += @{name="SQS Queue Depth Auto-Scaling"; context="Configure workers to auto-scale on SQS ApproximateNumberOfMessagesVisible."; criteria="performance, cost"; tree="Scaling metric?`n`nSQS ApproximateNumberOfMessagesVisible -> Best`nCustom backlog -> Alternative for DB queues`n`nScale-out threshold:`n`ntarget_latency x jobs_per_worker_per_min`nExample: 5min x 10 = scale at depth 50`n`nScale-in threshold?`n10% of scale-out threshold`n600s+ cooldown to prevent oscillation`n`nWorker type?`nSpot (70% discount) -> Stateless workers`nOn-Demand -> Time-critical jobs`nMixed (70/30) -> Balanced"; rationale="Latency-based scaling ensures workers are added before backlog exceeds acceptable delay."; default="Scale-out at depth 1000, add 2; scale-in at depth 100, remove 1; 600s cooldown"; risk="Too aggressive scale-in terminates workers mid-job. No auto-scaling = hours of backlog."}
            $trees += @{name="Priority Queue Separation"; context="Design separate scaling policies per queue priority."; criteria="performance, reliability"; tree="Multiple priorities?`n`nYES -> Separate queues and ASGs`nNO -> Single queue sufficient`n`nHigh priority (email):`nScale at depth 100, min=2, On-Demand`n`nLow priority (reports):`nScale at depth 5000, min=0, Spot`n`nNormal priority (notifications):`nScale at depth 500, 70% Spot + 30% On-Demand"; rationale="Separate ASGs per priority prevent low-priority jobs from starving high-priority queues."; default="3 tiers: high (On-Demand, min=2, depth=100); normal (mixed, depth=500); low (Spot, min=0, depth=5000)"; risk="Same scaling for all = cleanup blocks email delivery during batch spikes."}
        }
        '^vapor-lambda-invocation-cost' {
            $trees += @{name="Vapor Lambda Multiplier Calculation"; context="Calculate Vapor's true per-request cost including invocation multiplier."; criteria="cost"; tree="Measure multiplier?`n`nDivide Lambda invocations by HTTP requests`nAverage: 9x; Range 4-15x`n`nApply to cost:`nEffective cost/req = raw Lambda x multiplier`n`nCompare:`nVapor: $0.0000205/req (9x)`nCloud: ~$0.000004/req (5x cheaper)`nBref: $0.00000228/req (1x)`n`nDecision > $0.00005/req?`nYES -> Cloud or Bref cheaper`nNO -> Vapor competitive"; rationale="Vapor's 9x multiplier makes effective cost 9x raw Lambda. Primary reason Vapor becomes uneconomical above 20M req/month."; default="Always factor measured multiplier; re-measure quarterly as architecture evolves"; risk="Comparing without multiplier makes Vapor appear 3-5x cheaper than reality."}
            $trees += @{name="Vapor vs Bref Direct Lambda"; context="Choose between Vapor and Bref for Lambda-native Laravel."; criteria="cost, complexity"; tree="Request volume?`n`n< 5M req/month -> Vapor convenience justified`n5-20M -> Evaluate Bref (eliminates 9x multiplier)`n> 20M -> Cloud/Fargate likely cheapest`n`nDevOps capacity?`nLimited -> Vapor (managed, zero ops)`nAdequate -> Bref (more control, 1x multiplier)`nExperienced -> Custom Lambda deployment`n`nMultiplier impact:`nVapor: 9x; Bref: 1x (90% reduction)`n`nMigration path?`nVapor -> Bref -> Cloud for gradual optimization"; rationale="Bref gives direct Lambda without Vapor's architectural overhead. Each request = 1 invocation vs 9+ on Vapor."; default="Vapor for convenience < 5M req/month; Bref for cost > 5M; Cloud as ultimate destination"; risk="Vapor's 9x multiplier at 20M+ creates $5K+/month bills Bref would reduce by 80%."}
        }
        '^aurora-platform-v4' {
            $trees += @{name="Aurora v4 Upgrade Decision"; context="Decide when to upgrade Aurora v3 to v4 for immediate cost reduction."; criteria="cost, performance"; tree="Currently on Aurora?`n`nYES -> Upgrade to v4 immediately (28% cost reduction, free)`nNO -> Not applicable`n`nv4 available in region?`nYES -> Proceed with upgrade`nNO -> Wait for regional availability`n`nUpgrade approach?`nDuring maintenance window -> <30s downtime`nImmediate -> If >30 days to next window`n`nPost-upgrade:`nEvaluate downsizing after 2 weeks (27% faster queries may allow smaller instance)"; rationale="v4 delivers 28% cost reduction and 27% faster queries as a free, backward-compatible upgrade. No downside."; default="Upgrade immediately during next maintenance window; combine with Graviton for ~42% total savings"; risk="Delaying pays 28% more each month with zero benefit."}
            $trees += @{name="Post-v4 Instance Rightsizing"; context="Determine if Aurora instance can be downsized after v4 upgrade."; criteria="cost, performance"; tree="Current CPU utilization?`n`n< 60% -> Strong downsizing candidate`n60-80% -> May downsize; monitor carefully`n> 80% -> Keep current size`n`nMonitor 2 weeks post-upgrade?`nYES -> Collect CPU, memory, IOPS metrics`nNO -> Risky; wait for data`n`nDownsize trial results?`nCPU < 70% -> Keep smaller instance`nCPU > 80% -> Revert to original`n`nCombine with Graviton?`nYES -> v4 (28%) + Graviton (20%) = ~42% total reduction`nNO -> v4 only (28%)"; rationale="v4's 27% performance improvement may allow the same throughput on a smaller instance. Combined with Graviton, ~42% total reduction."; default="Monitor 2 weeks post-upgrade; evaluate downsizing one tier; combine with Graviton"; risk="Downsizing without 2 weeks monitoring risks insufficient capacity during peak hours."}
        }
        '^aurora-serverless-breakeven' {
            $trees += @{name="Serverless v2 vs Provisioned Decision"; context="Choose between Serverless v2 and provisioned Aurora based on traffic variability."; criteria="cost"; tree="Peak-to-trough ratio (90 days)?`n`n< 2:1 -> Provisioned + RI wins (20-60% cheaper)`n2:1-5:1 -> Model both options`n> 5:1 -> Serverless v2 wins`n`nRI coverage?`n3-year RI -> Provisioned 60% cheaper per compute-hour`nOn-Demand -> Provisioned ~$0.26 vs Serverless $0.12/ACU-hour`n`nMin ACU acceptable?`nYES -> Serverless v2 floor ~$43/month at 0.5 ACU`nNeed true zero -> Provisioned can be stopped`n`nHybrid considered?`nProvisioned writer + Serverless readers -> Often optimal for 2:1-5:1"; rationale="3:1 rule of thumb is for on-demand. With RIs, provisioned is 60% cheaper, requiring ~5:1 ratio for Serverless v2 to compete."; default="Provisioned + RI for < 2:1; Hybrid for 2:1-5:1; Serverless v2 for > 5:1"; risk="Serverless v2 for steady workloads (<2:1) costs 20-60% more than provisioned + RI."}
            $trees += @{name="Serverless v2 ACU Configuration"; context="Set optimal min/max ACU for Aurora Serverless v2."; criteria="cost, performance"; tree="Production database?`n`nYES -> Min ACU = working_set_GB / 2 (minimum 4 ACU)`nNO (dev/test) -> Min ACU = 0 (auto-pause)`n`nWorking set known?`nYES -> Min ACU = working_set / 2`nNO -> Start 4 ACU, monitor buffer pool hit ratio`n`nBuffer pool hit ratio > 95%?`nYES -> Min ACU sufficient`nNO -> Increase until >95%`n`nMax ACU?`nSet at peak + 20% headroom (prevents unbounded cost)"; rationale="Setting min ACU too low (0.5) causes buffer pool thrashing, increasing I/O costs by 50-200%. Each ACU provides ~2GB buffer pool."; default="Production: min 4 ACU; Dev: min 0 (auto-pause); max = peak + 20%; monitor buffer pool hit ratio"; risk="Setting min ACU to 0.5 in production causes thrashing with 50-200% higher I/O costs."}
        }
        '^aurora-serverless-v2' {
            $trees += @{name="Serverless v2 Configuration Strategy"; context="Configure ACU range and settings for optimal cost-performance."; criteria="cost, performance"; tree="Environment?`n`nProduction -> Min 4 ACU, max = peak + 20%`nDev/test -> Min 0 ACU (auto-pause), max 2-4 ACU`n`nI/O vs compute balance?`nI/O > 25% of compute -> I/O-Optimized ($0.156/ACU-hour)`nI/O < 25% -> Standard ($0.12/ACU-hour)`n`nBuffer pool hit ratio?`n> 95% = min ACU adequate`n< 95% = increase min ACU`n`nRDS Proxy?`nFactor 8 ACU minimum charge (~$300/month)`nUse PgBouncer for significant savings"; rationale="Serverless v2 has no RI, making it optimal for variable workloads but more expensive for steady workloads than provisioned+RI."; default="Production: min 4 ACU, I/O-Optimized if I/O > 25%; Dev: min 0 ACU, auto-pause"; risk="Min ACU 0.5 in production = buffer pool thrashing, 50-200% higher I/O costs."}
            $trees += @{name="I/O-Optimized vs Standard"; context="Choose between Standard and I/O-Optimized configurations."; criteria="cost"; tree="I/O charges as % of compute?`n`n< 15% -> Standard ($0.12/ACU-hour + I/O charges)`n15-25% -> Model both (breakeven zone)`n> 25% -> I/O-Optimized ($0.156/ACU-hour, no I/O charges)`n`nWorkload profile?`nRead-heavy, frequent queries -> Higher I/O; favor I/O-Optimized`nWrite-heavy -> Evaluate ratio`nBuffer pool thrashing -> Fix min ACU first`n`nSwitch possible?`nYES -> Zero downtime; start Standard, switch when threshold crossed"; rationale="I/O-Optimized eliminates per-I/O charges at 30% higher compute. Breakeven when I/O > ~25% of compute."; default="Start Standard; monitor I/O cost ratio; switch to I/O-Optimized when I/O > 25% of compute"; risk="Not evaluating I/O-Optimized when I/O high = paying 2-3x more in I/O than necessary."}
        }
        '^connection-limits-pricing' {
            $trees += @{name="Connection Limit Mitigation: Pooler vs Upgrade"; context="Choose between pooler and instance upgrade when approaching connection limits."; criteria="cost"; tree="Connection count vs max_connections?`n`n< 50% -> No action`n50-80% -> Monitor; plan pooler`n> 80% -> Action required`n`nSolution comparison:`nRDS Proxy: $15-30/month (managed)`nPgBouncer: ~$5/month (open source)`nInstance upgrade: $50-200+/month`n`nCost-optimal:`nAdd pooler first ($15-30/month)`nUpgrade only if more compute also needed`n`nImplementation:`nRDS Proxy -> Point Laravel to proxy endpoint`nPgBouncer -> Deploy on t4g.nano, pool size = 2-3x DB vCPUs"; rationale="RDS Proxy costs $15-30 vs instance upgrade $50-200+/month. Always pooler first, upgrade only if compute also needed."; default="Add RDS Proxy before upgrading instance; pooler saves $35-170+/month vs resizing"; risk="Upgrading for connections alone = paying for CPU/memory not needed."}
            $trees += @{name="max_connections Calculation"; context="Calculate and configure max_connections based on instance memory."; criteria="performance, reliability"; tree="Database engine?`n`nMySQL: max = LEAST(RAM_bytes/12582880, 5000)`nPostgreSQL: based on shared_buffers`n`nApp connection budget?`nWorkers + queue + admin reserve + background`nReserve 10-20% for admin`n`nBudget within max_connections?`nYES -> Configure in parameter group`nNO -> Add pooler or upgrade`n`nConnection timeout?`nLaravel: PDO::ATTR_TIMEOUT => 5 (5 seconds)"; rationale="max_connections directly tied to RAM. Each connection uses ~2-10MB. Overriding too high risks OOM."; default="Calculate from RAM formula; reserve 20% for admin; set 5s timeout"; risk="Setting too high on small instance causes OOM. Too low causes connection exhaustion."}
        }
        '^data-archival' {
            $trees += @{name="Data Archival Strategy Design"; context="Design data lifecycle with hot/warm/cold storage tiering."; criteria="cost, performance"; tree="Database size?`n`n< 50GB -> Plan for future`n50-200GB -> Implement next quarter`n> 200GB -> Implement immediately`n`nAccess patterns by age:`n0-6 months -> Hot (primary DB)`n6-24 months -> Warm (cheaper DB or S3)`n> 24 months -> Cold (S3/Glacier)`n`nCompliance retention?`n7-year -> Archive to S3/Glacier`nNone -> Can purge after business need`n`nPartition by date?`nYES -> Clean partition detachment`nNO -> Implement partitioning first"; rationale="Systematic archival reduces active DB size by 60-80%, enabling smaller instances and faster queries. Most Laravel apps access only last 30-90 days."; default="Partition by date; keep 6 months active; archive to S3/Parquet; test restoration quarterly"; risk="No archival = DB grows unbounded to 500GB+, slow queries, $1000+/month extra."}
            $trees += @{name="Archive Storage Tier Selection"; context="Choose storage for archived data by access frequency."; criteria="cost, performance"; tree="Access frequency?`n`nMonthly/quarterly -> S3 Standard or IA`nYearly/audit -> S3 Glacier`nNever (compliance) -> Glacier Deep Archive`n`nQuery mechanism?`nSQL needed -> Keep in cheap DB or Parquet + Athena`nRaw file -> S3 direct`nNo queries -> Glacier Deep Archive`n`nRestore SLA?`nMinutes -> S3 Standard/IA`n1-5 hours -> Glacier Flexible`n12+ hours -> Glacier Deep Archive (cheapest)`n`nFormat?`nParquet -> Compressed 70-80%, queryable`nCSV -> Universal, no schema, larger"; rationale="S3 $0.023/GB/month vs RDS $0.115-0.46/GB. Glacier Deep Archive $0.00099/GB is ~100x cheaper than DB storage."; default="Parquet on S3 Standard for 6-24 months; Glacier Deep Archive for 2+ years; Athena for queries"; risk="Archiving to CSV without schema = data can't be reliably restored."}
            $trees += @{name="Automated Archival Implementation"; context="Implement scheduled archival using Laravel commands and pruning."; criteria="reliability, cost"; tree="Soft-deleted models?`n`nYES -> Use Laravel Prunable trait`nNO -> Implement custom archive command`n`nArchival job?`n`nphp artisan app:archive-old-records` as daily scheduled task`n`nExport verification?`nVerify S3/Parquet created with correct data`nDelete from active DB only after verification`n`nQuarterly restoration test?`nRestore random subset`nVerify data integrity and completeness`nUpdate runbook"; rationale="Manual archival is error-prone. Automated scheduled jobs ensure regular archival without human intervention."; default="Schedule daily; use Prunable for soft-deletes; test restoration quarterly"; risk="Archiving without testing restoration = worthless if can't be recovered."}
        }
        '^index-tuning-cost' {
            $trees += @{name="Index Strategy Design"; context="Design indexing strategy balancing read performance vs write overhead."; criteria="performance, cost"; tree="Query pattern analysis done?`n`nYES -> Index for actual patterns`nNO -> Enable slow query log first`n`nColumn usage:`nWHERE -> Must index`nJOIN (foreign key) -> Must index`nORDER BY -> Index beneficial`nLow cardinality (< 100) -> Composite only`n`nComposite or single?`nSingle WHERE -> Single index`nMultiple WHERE -> Composite (order by cardinality)`nWHERE + ORDER BY -> Composite covering both`n`nWrite impact?`n< 5 indexes/table -> Acceptable`n5-10 -> Monitor write performance`n> 10 -> Review and consolidate"; rationale="Missing indexes cause full table scans on 1M+ rows. Each missing index adds 100ms+. But over-indexing slows writes 10-30% per index."; default="Index all foreign keys and WHERE clauses; composite for multi-column filters; monitor unused indexes"; risk="No FK indexes = full table scans on every JOIN. Too many composites = write overhead kills INSERT/UPDATE performance."}
            $trees += @{name="Unused Index Detection and Removal"; context="Identify and remove unused indexes to reduce write overhead."; criteria="performance, cost"; tree="Index usage stats checked?`n`nMySQL: sys.schema_unused_indexes`nPostgreSQL: pg_stat_user_indexes`n`nUnused indexes found?`nYES -> Review each for removal`nNO -> Current strategy efficient`n`nBefore dropping:`nVerify truly unused (30 days)`nDrop during non-peak hours`n`nAfter dropping:`nMonitor slow query log 1 week`nRe-add if regression appears"; rationale="Each unused index on write-heavy table costs 1-5% write overhead. Dropping them is free performance improvement."; default="Check for unused indexes quarterly; drop any not used in 30 days"; risk="Dropping seasonal index causes sudden query degradation."}
            $trees += @{name="Covering Index Decision"; context="Determine when to use covering indexes for hot queries."; criteria="performance, storage"; tree="Query is high-traffic (> 1000 req/s)?`n`nYES -> Covering index eliminates table access (90% I/O reduction)`nNO -> Simple index sufficient`n`nAll columns includable?`nYES -> Covering index possible`nNO -> Include via INCLUDE (PG) or extend composite (MySQL)`n`nStorage overhead OK?`nYES -> Create covering index`nNO -> Keep simple index`n`nDB engine difference?`nPostgreSQL -> INCLUDE keeps index smaller`nMySQL -> All columns in B-Tree (larger)"; rationale="Covering index stores all query columns, allowing query from index pages only. For hot queries, reduces I/O by 90%."; default="Covering indexes for hot queries (>1000 req/s); simple indexes for lower traffic"; risk="Adding covering indexes to every query = excessive storage and write overhead."}
        }
        '^query-optimization-cost' {
            $trees += @{name="N+1 Query Detection and Fix"; context="Identify and fix N+1 query problems in Eloquent."; criteria="performance, cost"; tree="Query count checked per page?`n`nYES -> Target < 10 queries`nNO -> Enable Debugbar or Telescope`n`nN+1 detected?`nYES -> Add eager loading with with()`nNO -> Profile next bottleneck`n`nDeep nested relations?`nYES -> Nested with() or lazy eager loading`nNO -> Simple with() solves it`n`nAPI resource optimization?`nLoad only requested relationships`nUse whenLoaded() conditionally"; rationale="N+1 with 50 parents + 5 children = 51 queries vs 2 queries. At 100 req/s, eliminating 49 queries/req removes 4,900 unnecessary queries/sec."; default="Eager load all relationships in loops; check query count in dev; target < 10 queries/page"; risk="N+1 in production = database CPU at 80%+ for what should be 2-3 queries."}
            $trees += @{name="Slow Query Resolution Process"; context="Identify and resolve slow queries using monitoring and EXPLAIN."; criteria="performance, cost"; tree="Slow query log enabled?`n`nYES -> Threshold: > 500ms`nNO -> Enable immediately`n`nEXPLAIN shows:`nFull table scan -> Add index`nTemporary table -> Rewrite query (avoid subqueries)`nFilesort -> Add index on ORDER BY`n`nQuery rewrites:`nSELECT * -> Select only needed columns`nWHERE FUNCTION(col) -> Sargable expression`nSubquery -> JOIN or EXISTS`n`nPost-fix:`nRe-check EXPLAIN`nVerify time < 100ms`nDeploy and monitor"; rationale="Queries >500ms are the 1% causing 90% of DB load. Fixing each can reduce database CPU by 20-50%."; default="Enable slow query log at 500ms; EXPLAIN all slow queries; fix full table scans first"; risk="Not monitoring slow queries = CPU steadily increases until performance crisis."}
            $trees += @{name="SELECT Optimization Strategy"; context="Optimize SELECT to minimize data transfer and processing."; criteria="performance, cost"; tree="SELECT * used?`n`nYES -> Replace with specific column list`nNO -> Good practice`n`nLarge dataset processing?`nYES -> Use chunk() instead of all()/get()`nNO -> Standard pagination fine`n`nPagination method?`nCursor pagination for large datasets`nStandard offset for small/medium`n`nRepeated queries?`nYES -> Cache with appropriate TTL`nNO -> Monitor for repeated patterns"; rationale="SELECT * on 50-column table where 3 are needed = 94% data waste. Multiplies I/O, network, memory by 10x."; default="Always specify columns; chunk() for large datasets; cursor pagination for large result sets"; risk="SELECT * on large tables causes 10x data transfer, 5x memory usage."}
        }
        '^neon-database-branching' {
            $trees += @{name="Database Branching Workflow"; context="Design branching workflow for development teams using Neon."; criteria="cost, productivity"; tree="Team size?`n`n1-3 devs -> 1-3 branches, manual`n4-10 devs -> Automated per developer`n> 10 -> CI/CD integrated lifecycle`n`nBranch source?`nProduction (copy-on-write) -> Realistic, free until modified`nSynthetic -> Consistent, no PII concerns`n`nLifecycle:`nCreate on PR open`nAuto-pause after 5 min idle`nAuto-delete after 7-14 day TTL or PR merge`n`nCI/CD integration?`nCreate at start, delete at end`nCost: ~$0.002 per run (5 min compute)"; rationale="Neon's copy-on-write branching provides instant isolated DBs at near-zero cost. Each developer gets their own DB without shared staging conflicts."; default="Branch from production; auto-pause 5 min; 7-day TTL; CI/CD create/delete per run"; risk="No TTL = orphaned branches accumulate storage costs. No auto-pause = compute 24/7."}
            $trees += @{name="Neon Branch Cost Control"; context="Configure compute limits and lifecycle policies for cost control."; criteria="cost, operational_overhead"; tree="Branch purpose?`n`nDeveloper -> 1 CU, 7-day TTL, 5-min auto-pause`nCI/CD -> 2 CU, create/delete per run`nPR preview -> 1-2 CU, delete on merge/close`nLong-term testing -> 2-4 CU, 30-day TTL`n`nCompute monitoring:`nFree tier: 100 compute-hours/month`n4 devs x 2hr/day x 30 = 240 hours (exceeds free)`nSet billing alert at 80%`n`nStorage delta monitoring:`nTrack per branch monthly`nInvestigate > 1GB delta branches"; rationale="Neon charges $0.106/CU-hour. Developer branches with auto-pause cost ~$6.36/month each. Without auto-pause: $76/month running 24/7."; default="Dev: 1 CU, 5-min auto-pause, 7-day TTL; CI/CD: create/delete per run; monitor monthly credits"; risk="No auto-pause = $76/month per dev branch running 24/7 when used 8 hours/day."}
        }
        '^neon-serverless-postgres' {
            $trees += @{name="Neon vs Aurora/RDS Environment Decision"; context="Determine when to use Neon vs Aurora for different environments."; criteria="cost, reliability"; tree="Environment?`n`nProduction (HA) -> Aurora/RDS (Neon not recommended primary)`nStaging -> Neon (scale-to-zero saves 60-70%)`nDevelopment -> Neon (free tier + branching)`nCI/CD -> Neon (branch create/delete, ~$0.002/run)`n`nDatabase size?`n< 200GB -> Neon suitable`n> 200GB -> Aurora/RDS better cost structure`n`nCold start tolerance?`nSub-1s OK -> Neon fine`n< 100ms -> Aurora always warm`n`nCost sensitivity?`nHigh -> Neon free tier + scale-to-zero`nLow -> Aurora (predictable)"; rationale="Neon's scale-to-zero and branching make it ideal for non-production, saving 60-70% vs always-on RDS. Aurora remains production recommendation."; default="Neon for dev/staging/CI/CD; Aurora/RDS for production; re-evaluate Neon annually"; risk="Neon for production HA = downtime risk without multi-AZ."}
            $trees += @{name="Neon Compute and Auto-Pause Configuration"; context="Configure compute units and auto-pause for cost optimization."; criteria="cost, performance"; tree="Environment?`n`nDevelopment -> 1 CU, 5-min auto-pause`nStaging -> 2-4 CU, 15-min auto-pause`nCI/CD -> 1-2 CU, delete after run`n`nCompute budget:`nFree tier: 100 compute-hours/month`nPaid: $0.106/CU-hour`nSet billing alert at 80% of free tier`n`nAuto-pause:`n5 min -> Good for individual dev`n15 min -> Better for staging`nDisable -> Latency-sensitive staging`n`nWeekly cleanup:`nReview stale branches`nDelete orphans`nDocument branch owners"; rationale="Neon charges compute only when active. Auto-pause after 5 min reduces costs by 60-70% for databases used 8 hours/day but idle the rest."; default="Dev: 1 CU, 5-min auto-pause; Staging: 2-4 CU, 15-min auto-pause; monitor monthly credits"; risk="No auto-pause = 3-4x more compute cost than necessary."}
        }
        '^aurora-serverless-v2' {
            # Already handled above
        }
        default {
            $trees += @{name="Cost Optimization Strategy Selection"; context="Choose the most appropriate cost optimization strategy for this specific area."; criteria="cost, performance, complexity"; tree="Current monthly spend?`n`n< $100/month -> Simple config changes`n$100-$500/month -> Implement standard best practices`n$500-$1000/month -> Model each optimization option`n> $1000/month -> Implement all applicable optimizations`n`nOptimization complexity?`nConfig change -> Implement immediately (highest ROI)`nArchitecture change -> Plan and schedule`nRequires third-party -> Coordinate dependencies`n`nPerformance impact?`nNo impact or improves -> Implement immediately`nMay degrade -> Test in staging first`n`nRisk level?`nLow -> Implement and move on`nMedium -> Validate with monitoring before/after`nHigh -> Create rollback plan before implementation"; rationale="Cost optimization should be prioritized by ROI. Configuration changes with no performance impact and high savings should be implemented immediately."; default="Start with config changes (highest ROI); validate with monitoring; create rollback plans for high-risk changes"; risk="Implementing high-risk changes without testing can cause production incidents costing more than the optimization saves."}
            $trees += @{name="Resource Right-Sizing Decision"; context="Determine optimal resource allocation from actual usage patterns."; criteria="cost, performance"; tree="Current P95 utilization (2 weeks)?`n`n< 30% -> Downsize one tier`n30-60% -> Appropriate sizing`n60-80% -> Plan for scaling`n> 80% -> Up-size or scale out`n`nGrowth trajectory?`nStable -> Right-size to current needs`nGrowing < 10%/month -> Add 3-month buffer`nGrowing > 10%/month -> Add 6-month buffer`n`nCommitment options?`n1-year -> ~40% discount`n3-year -> ~60% discount`nNone -> Maximum flexibility`n`nAuto-scaling available?`nYES -> Size for baseline; auto-scaling handles peaks`nNO -> Size for P95 + 20% headroom"; rationale="Right-sizing eliminates 30-50% waste from over-provisioned resources. Two-week monitoring reveals true baseline and peak usage."; default="Monitor 2 weeks; right-size to P95 + 20%; use commitment discounts for stable workloads"; risk="Sizing for peak without auto-scaling wastes 40-70% of resource budget."}
            $trees += @{name="Commitment Discount Purchase Decision"; context="Determine whether to buy Reserved Instances or Savings Plans."; criteria="cost, flexibility"; tree="Workload runs 24/7?`n`nYES -> Eligible for commitments`nNO (dev/staging) -> On-demand better`n`nWorkload stability?`nStable, predictable -> 3-year (max savings)`nGrowing/changing -> 1-year or Compute Savings Plans`nUncertain -> On-demand or no-upfront plans`n`nPayment preference?`nAll upfront -> Max discount, higher cash outlay`nPartial upfront -> Good balance`nNo upfront -> Lower savings, no capital`n`nFlexibility needed?`nInstance type may change -> Compute Savings Plans`nRegion may change -> Compute Savings Plans`nEverything fixed -> Reserved Instances (highest discount)"; rationale="Commitment discounts reduce compute costs by up to 66%. Compute Savings Plans offer flexibility across instances and services."; default="3-year Compute Savings Plans for flexibility; RIs for completely fixed instance types"; risk="Buying 3-year RIs for resources that get downsized = paying for unused capacity. No commitment = paying 60% more."}
        }
    }
    
    # Ensure we have at least 2 trees (some might have matched earlier cases)
    if ($trees.Count -lt 2) {
        $trees += @{name="Cost Optimization Strategy"; context="Choose appropriate cost optimization approach for this specific resource."; criteria="cost, performance, complexity"; tree="Current monthly spend?`n`n< $100 -> Simple config changes`n$100-$500 -> Standard best practices`n$500-$1000 -> Model each option`n> $1000 -> All applicable optimizations`n`nComplexity?`nConfig change -> Implement immediately`nArchitecture -> Plan and schedule`nThird-party -> Coordinate dependencies`n`nPerformance impact?`nNo impact -> Implement now`nMay degrade -> Test in staging`n`nRisk?`nLow -> Implement`nMedium -> Monitor before/after`nHigh -> Create rollback plan"; rationale="Prioritize by ROI. Config changes with no performance impact and high savings should be implemented immediately."; default="Start with config changes (highest ROI); validate with monitoring; rollback plans for high-risk changes"; risk="High-risk changes without testing can cause incidents costing more than savings."}
    }
    if ($trees.Count -lt 2) {
        $trees += @{name="Resource Sizing Decision"; context="Determine optimal resource allocation."; criteria="cost, performance"; tree="Current utilization (2-week P95)?`n`n< 30% -> Downsize`n30-60% -> Appropriate`n60-80% -> Plan for scaling`n> 80% -> Up-size`n`nGrowth trajectory?`nStable -> Right-size to current`nGrowing -> Add growth buffer`n`nCommitment options?`n1-year -> ~40% discount`n3-year -> ~60% discount`n`nAuto-scaling?`nYES -> Size for baseline`nNO -> Size for P95 + 20%"; rationale="Right-sizing eliminates 30-50% waste from over-provisioned resources."; default="Monitor 2 weeks; right-size to P95 + 20%; use commitments for stable workloads"; risk="Sizing for peak without auto-scaling wastes 40-70% of resource budget."}
    }
    
    # Write the file
    $domainDisp = "Cost Resource Optimization"
    $subDisp = $ku.Subdomain
    
    Write-TreeFile -Path $outPath -Trees $trees -Title $title -Domain $domainDisp -Subdomain $subDisp
    
    Write-Host "[$count/$total] $($ku.Subdomain)/$($ku.KU)"
}

Write-Host "`n=== COMPLETE: Generated $total files ==="
